---
version: 2.1

jobs:

  test:
    parameters:
      ruby:
        type: string
      rails:
        type: string
    docker:
      - image: circleci/ruby:<< parameters.ruby >>-stretch
      - image: circleci/mysql:5.7-ram
    environment:
      BUNDLE_GEMFILE: gemfiles/rails<< parameters.rails >>.gemfile
    steps:
      - checkout
      - run: sudo apt install -y default-mysql-client
      - run:
          name: Install the correct version of Bundler
          command: |
            bundler_version=$(grep -A1 'BUNDLED WITH' ${BUNDLE_GEMFILE:-Gemfile}.lock | tail -n1 | sed -e 's/^[[:space:]]*//')
            gem install --no-document bundler -v $bundler_version
      - run: bundle install
      - run:
          name: Wait for MySQL to be ready
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
      - run:
          name: Create user 'john-doe' in MySQL
          command: mysql --host 127.0.0.1 --user root -e "CREATE USER 'john-doe'@'127.0.0.1'; GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,INDEX ON *.* TO 'john-doe'@'127.0.0.1'; FLUSH PRIVILEGES;"
      - run: bundle exec rake test

  rubocop:
    docker:
      - image: circleci/ruby
    environment:
      BUNDLE_GEMFILE: gemfiles/rails5.2.gemfile
    steps:
      - checkout
      - run:
          name: Install the correct version of Bundler
          command: |
            bundler_version=$(grep -A1 'BUNDLED WITH' ${BUNDLE_GEMFILE:-Gemfile}.lock | tail -n1 | sed -e 's/^[[:space:]]*//')
            gem install --no-document bundler -v $bundler_version
      - run: bundle install
      - run: bundle exec rubocop

workflows:
  version: 2
  build:
    jobs:
      - test:
          matrix:
            parameters:
              ruby: ["2.4", "2.5", "2.6"]
              rails: ["4.2", "5.1", "5.2", "6.0"]
            exclude:
              - ruby: "2.4"
                rails: "6.0"
      - rubocop
